string = "GGTATACAGCAATTGGAACGAGAGGGTATACGGTATACGGTATACGAACGAGAGTGGTTTGGGTATACCGAACCAGAACGAGAGGAACGAGAGAGCAATTGTGGTTTGGAACGAGAGCGAACCAGAACGAGAGCGAACCAGGTATACAGCAATTGGGTATACCGAACCACGAACCATGGTTTGAGCAATTGCGAACCAGGTATACGAACGAGAGTGGTTTGGGTATACTGGTTTGCGAACCAGAACGAGAGGAACGAGAGGAACGAGAGCGAACCATGGTTTGTGGTTTGGGTATACTGGTTTGGAACGAGAGAGCAATTGGGTATACTGGTTTGTGGTTTGGAACGAGAGCGAACCATGGTTTGTGGTTTGCGAACCAGGTATACAGCAATTGGGTATACGAACGAGAGGGTATACTGGTTTGGGTATACCGAACCAGAACGAGAGAGCAATTGGGTATACTGGTTTGAGCAATTGGGTATACCGAACCACGAACCAGAACGAGAGGGTATACGGTATACAGCAATTGAGCAATTGGAACGAGAGAGCAATTGCGAACCAGAACGAGAGAGCAATTGTGGTTTGGAACGAGAGTGGTTTGGAACGAGAGGAACGAGAGGAACGAGAGCGAACCAGGTATACGGTATACGGTATACCGAACCATGGTTTGCGAACCAGGTATACGAACGAGAGGAACGAGAGCGAACCATGGTTTGCGAACCATGGTTTGGGTATACGAACGAGAGCGAACCACGAACCACGAACCATGGTTTGTGGTTTGGGTATACGGTATAC"
k = 13

def frequentWords(string, k):
	res = {}
	for i in range(0, len(string) - k - 1):
		word = string[i:(i + k)]
		if word in res:
			res[word] +=1
		else:
			res[word] = 1

	maxValue = max(res.values())
	result = [key for key in res.keys() if res[key] == maxValue]

	return result

print frequentWords(string, k)