import itertools

string = "GTGTCTTGAAATACATGCTTTCGAGGGTCAACCTTGTTACATTCGTGATTGAGGAGTGCGATCGACGAGATATACTAGCTCTGTAGGAGGATATATAAGCATGGGCCCTTGCATACGAATAAAACCCAGGAGACATCGAATCCTACCCGTCCCTTTACATACCGTGTTGTCAGACCCTTTCGAGTGGCTAGGTTTAACTGACCCCGCGCCCAATCGAGGTAAGGCCGAGCTCGAAGTGTGCGGGCTGCCGGCAATGGCATTATTTGTTAATATGTATAGGAGCAATGTCTCGTGATGAAGAGTAGTAATCCATAAAGCCACCCTCCTGACGACAGGGAACTGTCTTACTAAAGACGCTCAATACTACCCTCTTGTGTCACGTCGAATAATATAATTCTCCCGTTTGGCGCAACCGGCGCGCCCAAAGCGGTTATTTGGAATCAACATGACTCATGGTTATGATGATACACTTACCGACCTCACCACGTTAAACTCCTGTTGGTGTAGCTTGAGCCGGATAGACGAGGAAGTTTTTAAGAACTATAACATTCGCAGAGCCTACATGTATACACGGGCTCTATATAGAACGAGGTGCGGGCATTTCGCCTGGTTCGAAGGGCCTACTACTAGGTGCGGGTAACCCAGTAAAAAAAGTAGCAGGAACA"
k = 6



def freqArray(string, k):
	array = []
	words = map(''.join, itertools.product('ACGT', repeat = k))
	for word in words:
		count = 0
		for i in range(0, len(string) - k + 1):
			kmer = string[i:i+k]
			if word == kmer:
				count += 1
		array.append(count)
		res = " ".join(str(val) for val in array)
	return res

print freqArray(string, k)